# Generated by Django 5.2.8 on 2025-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idalimento', models.AutoField(db_comment='Identificador único del alimento.', primary_key=True, serialize=False)),
                ('fechadecaducidad', models.DateField(db_comment='Fecha de caducidad del alimento.')),
                ('nombre', models.CharField(db_comment='Nombre del alimento.', max_length=20)),
                ('tipo', models.CharField(db_comment='Tipo o categoría del alimento.', max_length=20)),
                ('precio', models.FloatField(db_comment='Precio del alimento; debe ser un valor positivo.')),
            ],
            options={
                'db_table': 'alimento',
                'db_table_comment': 'Tabla que contiene los alimentos ofrecidos por los vendedores en el evento.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idpersona', models.AutoField(db_comment='Identificador único del vendedor (PK).', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Nombre del vendedor.', max_length=100)),
                ('apellidomaterno', models.CharField(db_comment='Apellido materno del vendedor.', max_length=100)),
                ('apellidopaterno', models.CharField(db_comment='Apellido paterno del vendedor.', max_length=100)),
                ('fechanacimiento', models.DateField(db_comment='Fecha de nacimiento del vendedor.')),
                ('sexo', models.CharField(db_comment='Sexo del vendedor.', max_length=10)),
                ('calle', models.CharField(db_comment='Calle de residencia del vendedor.', max_length=100)),
                ('colonia', models.CharField(db_comment='Colonia de residencia del vendedor.', max_length=100)),
                ('ciudad', models.CharField(db_comment='Ciudad de residencia del vendedor.', max_length=100)),
                ('codigopostal', models.IntegerField(db_comment='Código postal del vendedor.')),
                ('numinterior', models.IntegerField(db_comment='Número interior del vendedor.')),
                ('numexterior', models.IntegerField(db_comment='Número exterior del vendedor.')),
                ('ubicacion', models.CharField(db_comment='Ubicación asignada del vendedor.', max_length=100)),
            ],
            options={
                'db_table': 'vendedor',
                'db_table_comment': 'Tabla para almacenar la información de los venderores.',
                'managed': False,
            },
        ),
    ]
